// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddEndpoint(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function ClearLogs():Promise<void>;

export function GetConfig():Promise<string>;

export function GetLogLevel():Promise<number>;

export function GetLogs():Promise<string>;

export function GetLogsByLevel(arg1:number):Promise<string>;

export function GetStats():Promise<string>;

export function OpenURL(arg1:string):Promise<void>;

export function RemoveEndpoint(arg1:number):Promise<void>;

export function SetLogLevel(arg1:number):Promise<void>;

export function ToggleEndpoint(arg1:number,arg2:boolean):Promise<void>;

export function UpdateConfig(arg1:string):Promise<void>;

export function UpdateEndpoint(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function UpdatePort(arg1:number):Promise<void>;
