// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddEndpoint(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddEndpoint'](arg1, arg2, arg3);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function RemoveEndpoint(arg1) {
  return window['go']['main']['App']['RemoveEndpoint'](arg1);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function UpdateEndpoint(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateEndpoint'](arg1, arg2, arg3, arg4);
}

export function UpdatePort(arg1) {
  return window['go']['main']['App']['UpdatePort'](arg1);
}
