// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddEndpoint(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function BackupToWebDAV(arg1:string):Promise<void>;

export function ClearLogs():Promise<void>;

export function DeleteWebDAVBackups(arg1:Array<string>):Promise<void>;

export function DetectWebDAVConflict(arg1:string):Promise<string>;

export function GenerateMockArchives(arg1:number):Promise<string>;

export function GetArchiveData(arg1:string):Promise<string>;

export function GetArchiveTrend(arg1:string):Promise<string>;

export function GetConfig():Promise<string>;

export function GetCurrentEndpoint():Promise<string>;

export function GetLanguage():Promise<string>;

export function GetLogLevel():Promise<number>;

export function GetLogs():Promise<string>;

export function GetLogsByLevel(arg1:number):Promise<string>;

export function GetStats():Promise<string>;

export function GetStatsDaily():Promise<string>;

export function GetStatsMonthly():Promise<string>;

export function GetStatsTrend():Promise<string>;

export function GetStatsTrendByPeriod(arg1:string):Promise<string>;

export function GetStatsWeekly():Promise<string>;

export function GetStatsYesterday():Promise<string>;

export function GetSystemLanguage():Promise<string>;

export function GetTheme():Promise<string>;

export function GetThemeAuto():Promise<boolean>;

export function GetVersion():Promise<string>;

export function HideWindow():Promise<void>;

export function ListArchives():Promise<string>;

export function ListWebDAVBackups():Promise<string>;

export function OpenURL(arg1:string):Promise<void>;

export function Quit():Promise<void>;

export function RemoveEndpoint(arg1:number):Promise<void>;

export function ReorderEndpoints(arg1:Array<string>):Promise<void>;

export function RestoreFromWebDAV(arg1:string,arg2:string):Promise<void>;

export function SetCloseWindowBehavior(arg1:string):Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;

export function SetLogLevel(arg1:number):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function SetThemeAuto(arg1:boolean):Promise<void>;

export function ShowWindow():Promise<void>;

export function SwitchToEndpoint(arg1:string):Promise<void>;

export function TestEndpoint(arg1:number):Promise<string>;

export function TestWebDAVConnection(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ToggleEndpoint(arg1:number,arg2:boolean):Promise<void>;

export function UpdateConfig(arg1:string):Promise<void>;

export function UpdateEndpoint(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<void>;

export function UpdatePort(arg1:number):Promise<void>;

export function UpdateWebDAVConfig(arg1:string,arg2:string,arg3:string):Promise<void>;
