// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddEndpoint(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddEndpoint'](arg1, arg2, arg3);
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetLogLevel() {
  return window['go']['main']['App']['GetLogLevel']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetLogsByLevel(arg1) {
  return window['go']['main']['App']['GetLogsByLevel'](arg1);
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function RemoveEndpoint(arg1) {
  return window['go']['main']['App']['RemoveEndpoint'](arg1);
}

export function SetLogLevel(arg1) {
  return window['go']['main']['App']['SetLogLevel'](arg1);
}

export function ToggleEndpoint(arg1, arg2) {
  return window['go']['main']['App']['ToggleEndpoint'](arg1, arg2);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function UpdateEndpoint(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateEndpoint'](arg1, arg2, arg3, arg4);
}

export function UpdatePort(arg1) {
  return window['go']['main']['App']['UpdatePort'](arg1);
}
