// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddEndpoint(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['AddEndpoint'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function BackupToWebDAV(arg1) {
  return window['go']['main']['App']['BackupToWebDAV'](arg1);
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function DeleteWebDAVBackups(arg1) {
  return window['go']['main']['App']['DeleteWebDAVBackups'](arg1);
}

export function DetectWebDAVConflict(arg1) {
  return window['go']['main']['App']['DetectWebDAVConflict'](arg1);
}

export function GenerateMockArchives(arg1) {
  return window['go']['main']['App']['GenerateMockArchives'](arg1);
}

export function GetArchiveData(arg1) {
  return window['go']['main']['App']['GetArchiveData'](arg1);
}

export function GetArchiveTrend(arg1) {
  return window['go']['main']['App']['GetArchiveTrend'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCurrentEndpoint() {
  return window['go']['main']['App']['GetCurrentEndpoint']();
}

export function GetLanguage() {
  return window['go']['main']['App']['GetLanguage']();
}

export function GetLogLevel() {
  return window['go']['main']['App']['GetLogLevel']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetLogsByLevel(arg1) {
  return window['go']['main']['App']['GetLogsByLevel'](arg1);
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetStatsDaily() {
  return window['go']['main']['App']['GetStatsDaily']();
}

export function GetStatsMonthly() {
  return window['go']['main']['App']['GetStatsMonthly']();
}

export function GetStatsTrend() {
  return window['go']['main']['App']['GetStatsTrend']();
}

export function GetStatsTrendByPeriod(arg1) {
  return window['go']['main']['App']['GetStatsTrendByPeriod'](arg1);
}

export function GetStatsWeekly() {
  return window['go']['main']['App']['GetStatsWeekly']();
}

export function GetStatsYesterday() {
  return window['go']['main']['App']['GetStatsYesterday']();
}

export function GetSystemLanguage() {
  return window['go']['main']['App']['GetSystemLanguage']();
}

export function GetTheme() {
  return window['go']['main']['App']['GetTheme']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function ListArchives() {
  return window['go']['main']['App']['ListArchives']();
}

export function ListWebDAVBackups() {
  return window['go']['main']['App']['ListWebDAVBackups']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RemoveEndpoint(arg1) {
  return window['go']['main']['App']['RemoveEndpoint'](arg1);
}

export function ReorderEndpoints(arg1) {
  return window['go']['main']['App']['ReorderEndpoints'](arg1);
}

export function RestoreFromWebDAV(arg1, arg2) {
  return window['go']['main']['App']['RestoreFromWebDAV'](arg1, arg2);
}

export function SetCloseWindowBehavior(arg1) {
  return window['go']['main']['App']['SetCloseWindowBehavior'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function SetLogLevel(arg1) {
  return window['go']['main']['App']['SetLogLevel'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function SwitchToEndpoint(arg1) {
  return window['go']['main']['App']['SwitchToEndpoint'](arg1);
}

export function TestEndpoint(arg1) {
  return window['go']['main']['App']['TestEndpoint'](arg1);
}

export function TestWebDAVConnection(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestWebDAVConnection'](arg1, arg2, arg3);
}

export function ToggleEndpoint(arg1, arg2) {
  return window['go']['main']['App']['ToggleEndpoint'](arg1, arg2);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function UpdateEndpoint(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['UpdateEndpoint'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function UpdatePort(arg1) {
  return window['go']['main']['App']['UpdatePort'](arg1);
}

export function UpdateWebDAVConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateWebDAVConfig'](arg1, arg2, arg3);
}
